version: "3.1"
services:
    ### Маршрутизация нескольких проектов. Желательно удалить, если в контейнере будет не больше одного проекта
    nginx-proxy:
        image: jwilder/nginx-proxy # или nginx:latest
        # Порты для вывода проектов (реальный : виртуальный)
        ports:
            - "80:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./hosts:/etc/nginx/conf.d # на всякий случай
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /path/to/vhost.d:/etc/nginx/vhost.d:ro
    ###

    ### Проекты
    comagic:
        build: .
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            # Путь к проекту на реальной машине : путь к проекту на виртуальной машине
            - ./www/comagic:/var/www/html/
        # зависимость описанного ниже
        links:
            - db
        networks:
            - default
        # ограничение на показ. Необходимо указать виртуальные хосты, где будет разрешен показ. Если ничего не указывать, то сайт будет выводиться на всех хостах
        environment:
            - VIRTUAL_HOST=comagic.local

    komstroyproekt:
        build: .
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            # Путь к проекту на реальной машине : путь к проекту на виртуальной машине
            - ./www/komstroyproekt:/var/www/html/
        # зависимость описанного ниже
        links:
            - db
        networks:
            - default
        # ограничение на показ. Необходимо указать виртуальные хосты, где будет разрешен показ. Если ничего не указывать, то сайт будет выводиться на всех хостах
        environment:
            - VIRTUAL_HOST=komstroyproekt.local
    ###

    ### Дополнительные модули
    db:
        image: mysql:8.0
        ports:
            - "6033:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: mysql
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: mysql
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - ./data_mysql:/var/lib/mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80 # Порт для вывода phpmyadmin (реальный : виртуальный)
        environment:
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: mysql
    ###
        
